name: Unit test

on:
  push:
    branches:
      - main
      - master
      
jobs:

  test_python_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Test projects
        run: |
          python ./python/factorial/test_factorial.py
          python ./python/fibonacci/test_fibonacci.py
          python ./python/odd_or_even/test_odd_or_even.py
          python ./python/prime_number/test_prime_number.py
          python ./python/ini_file_parser/test_ini_file_parser.py
          python ./python/string_generator/test_string_generator.py
          
          # Projects with libraries dependencies
          pip install -r ./python/yaml_file_parser/requirements.txt
          python ./python/yaml_file_parser/test_yaml_file_parser.py
          
          pip install -r ./python/klse_screener/requirements.txt
          python ./python/klse_screener/test_klse_screener.py

  test_csharp_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dotnet
        uses: actions/setup-dotnet@v4
      - name: Check dotnet version
        run: |
          dotnet --version